### ISSUE TITLE
Moderation Module

### ISSUE THREAD

**Issue by immervoll** [immervoll/community-bot#8]
#### Commands:

- [ ] `/ban <member> <reason> <opt: duration>`
- [ ] `/unban <member> <reason>`
- [ ] `/kick <member> <reason>`
- [ ] `/warn <member> <reason>` --> Warns member
- [ ]  `/warns <member>` --> Show past warns
- [ ] `/purge <opt:meber || opt: ammount>` --> deletes `ammount` of messages in channel *or* all messages by `member`in the channel
- [ ] `/createticket <member> <opt:topic>` --> creates ticket with `member`. If used as reaction to a message, the original message content will moved to the ticket aswell
- [ ] `/addmember <member>` --> Adds `member` to ticket & greets him.
- [ ] `/lockticket`
- [ ] `/unlockticket`
- [ ] `/closerequest`
- [ ] `/forceclose` --> locks ticket, forces promt for deletion / archive
- [ ] `/protocol <ticketchannel`> --> returns protocol of the ticket.

#### Tasks

- [ ] Auto Kick / Ban at X Warns
- [ ] Auto unban if ban expired
- [ ] Monitor for Scam links
#### Events:
- [ ] Join / Leave / Mod action logging
